# Generated by Django 2.0.2 on 2018-02-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_password',
            field=models.CharField(default='demo', max_length=100),
            preserve_default=False,
        ),
    ]
